# Generated by Django 5.0.2 on 2024-08-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_post_image_delete_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk']},
        ),
    ]
