# Generated by Django 5.0.2 on 2024-08-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
    ]
