# Generated by Django 5.0.2 on 2024-08-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
