# Generated by Django 5.0.2 on 2024-09-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
