# 모든 서버 블록에서 사용하는 전역 access log
access_log /var/log/nginx/access.log;

# 모든 서버 블록에서 사용하는 전역 error log
error_log /var/log/nginx/error.log warn;

server {
    listen 80;
    server_name your-server-ip-or-domain;
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forward_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /usr/src/app/_static/;
    }
    location /media {
        alias /usr/src/app/_media/;
    }
}
