# Generated by Django 5.0.2 on 2024-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_subuser_main_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
