# Generated by Django 5.0.2 on 2024-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_blog_app_po_slug_c9147f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('youtube', 'Youtube')], max_length=50),
        ),
    ]
