# Generated by Django 5.0.2 on 2024-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tree', '0002_alter_node_name_alter_node_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/focus_icon/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='node',
            name='main_text',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
