# Generated by Django 5.0.2 on 2024-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tree', '0003_node_image_node_main_text_node_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(default='', max_length=9),
        ),
    ]
