# Generated by Django 5.0.2 on 2024-09-01 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tree', '0004_alter_node_node_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parents', models.ManyToManyField(related_name='children', through='focus_tree.NodeRelation', to='focus_tree.treenode')),
            ],
            options={
                'verbose_name': 'Tree Node',
                'verbose_name_plural': 'Tree Nodes',
            },
        ),
        migrations.AddField(
            model_name='noderelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='focus_tree.treenode'),
        ),
        migrations.AddField(
            model_name='noderelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='focus_tree.treenode'),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AlterUniqueTogether(
            name='noderelation',
            unique_together={('parent', 'child')},
        ),
    ]
