# Generated by Django 5.0.2 on 2024-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tree', '0005_noderelation_treenode_noderelation_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='treenode',
            name='main_text',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='treenode',
            name='node_id',
            field=models.CharField(default='defalut', max_length=9),
        ),
        migrations.AddField(
            model_name='treenode',
            name='position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treenode',
            name='position_y',
            field=models.IntegerField(default=0),
        ),
    ]
