# Generated by Django 5.0.2 on 2024-09-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tree', '0006_treenode_image_treenode_main_text_treenode_node_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='focus_tree/images/'),
        ),
    ]
