# Generated by Django 5.0.2 on 2024-10-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tree', '0008_alter_treenode_image_tree_treenode_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderelation',
            name='tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='focus_tree.tree'),
        ),
    ]
