# Generated by Django 5.0.2 on 2024-10-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tree', '0009_noderelation_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='node_id',
        ),
    ]
